### ISSUE TITLE
addTrackToDB function

### ISSUE THREAD

**Issue by boosth** [resonatecoop/resonate-crowdfund-uploader#3]

**Comment by boosth** [comment]
--- direct-s3-upload-form.php-orig	2016-11-22 15:26:17.260800570 +0000
+++ direct-s3-upload-form.php	2016-11-22 15:31:01.711985914 +0000
@@ -9,6 +9,7 @@
 get_currentuserinfo();
 
 $current_user = wp_get_current_user();
+//$current_user->ID = 1244;
 $uuid4 = Uuid::uuid4();
 $awsUuid = $uuid4->toString();
 $audioForm = new Signature(
@@ -35,7 +36,7 @@
 $visualForm = new Signature(
     getenv('AWS_ACCESS_KEY_ID'),
     getenv('AWS_SECRET_ACCESS_KEY'),
-    getenv('AWS_S3_BUCKET_NAME'),
+    "resonate-dev", //getenv('AWS_S3_BUCKET_NAME'),
     getenv('AWS_S3_REGION'),
     [
         'acl' => 'public-read',
@@ -524,6 +525,46 @@
             localStorage.setItem('uploadedTracks', JSON.stringify(tracks))
         }
 
+        function addTrackToDB(){
+	    var realArtistField = $('[name=x-amz-meta-artist]')[ 0 ].value
+            var realTrackNameField = $('[name=x-amz-meta-track-name]')[ 0 ].value
+            var realAlbumField = $('[name=x-amz-meta-album]')[ 0 ].value
+            var realTrackDurationField = $('[name=x-amz-meta-track-duration]')[ 0 ].value
+            var realTrackOwnerId = $('[name=x-amz-meta-owner-id]')[ 0 ].value
+            var realTrackAudioKey = $('#audio-form [name=key]')[ 0 ].value
+            var realTrackVisualKey = $('[name=x-amz-meta-visual-key]')[ 0 ].value
+            
+	    var trackObject = {
+                "name": realTrackNameField,
+                "album": realAlbumField,
+                "artist": realArtistField,
+		"duration": realTrackDurationField,
+		"uid": realTrackOwnerId,
+                "audioKey": realTrackAudioKey ,
+                "visualKey": realTrackVisualKey,
+ 		"isUploaded": "0",
+            }
+
+	    jTrack = JSON.stringify(trackObject)
+	    console.log(jTrack);
+	    //alert(realArtistField+" | "+realTrackNameField+" | "+realAlbumField+" | "+realTrackDurationField+" | "+realTrackOwnerId+" | "+realTrackAudioKey+" | "+realTrackVisualKey)
+
+	    jQuery.ajax({
+    		type: "POST",
+    		url: "/tracklist.php?j="+jTrack,
+    		success: function(data){
+			console.log(data);
+		//	alert(data);
+		},
+    		failure: function(errMsg) {
+        		console.log(errMsg);
+    		}
+	    });
+
+	}
+
+
+
         function submitForm () {
             var validForm = validateForm()
             var fieldsCopied = copyFormFields()
@@ -534,6 +575,9 @@
                 console.log('%call form fields are filled out & valid.', 'color: #00FF00')
                 console.log('%cattempting audio form submission...', 'font-weight: bold')
                 toggleUploadState()
+
+		addTrackToDB();
+
                 $('.upload-button')[ 0 ].removeEventListener('click', submitClick)
                 jQuery.ajax({
                     type: 'POST',

**Comment by haywirez** [comment]
Can you please create a pull request instead?
