### ISSUE TITLE
Source code being displayed on webpage

### ISSUE THREAD

**Issue by chrishobcroft** [resonatecoop/resonate-crowdfund-uploader#4]
The following text is appearing on https://resonate.is/profile/1270/ in clear text - I'm guessing this is some code which should be pulling in some assets for display? This is on Chrome for Windows.

<a href="https://seedbloom.it/projects/resonate/" target="_blank"><img class="alignnone wp-image-3196 size-full" src="https://resonate.is/wp-content/uploads/2016/10/Own-the-next-generation-of-streaming-music-04.png" alt="own-the-next-generation-of-streaming-music-04" width="260" height="462" /></a>

**Comment by chrishobcroft** [comment]
For clarity - the image is not being displayed, only the html code: 

a href="https://seedbloom.it/projects/resonate/" target="_blank"><img class="alignnone wp-image-3196 size-full" src="https://resonate.is/wp-content/uploads/2016/10/Own-the-next-generation-of-streaming-music-04.png" alt="own-the-next-generation-of-streaming-music-04" width="260" height="462" /></a>

**Comment by chrishobcroft** [comment]
For screenshot, see this link, and the area highlighted in red:

https://ipfs.io/ipfs/QmX5AV4R9CkKbKmWCgPuWbAtQV1966kTfSn8shk4wnd218

**Comment by peteratomic** [comment]
Chris, are you still seeing this? Have a feeling you were seeing it the moment Patrick was working on it.

**Comment by chrishobcroft** [comment]
Unable to reproduce
