### ISSUE TITLE
Display of player UI is a bit messy :)

### ISSUE THREAD

**Issue by chrishobcroft** [resonatecoop/resonate-crowdfund-uploader#5]
The UI of the player seems to be a bit messy:

1. there are scroll bars when there doesn't need to be

2. The text in the playlist is not aligned with the images - covered up in some way

3. The image for the 4th track is missing (perhaps it is missing)

https://ipfs.io/ipfs/QmUDVLceqCaMHHPXM4gy98zsxNk1Ev1PxKm2NhmzkQkziV

**Comment by chrishobcroft** [comment]
Re: point #3 - it seems that the images and the track titles are out of step by 1 step - 4 tracks, 4 images, but the tracks are not aligned with the images - see below for another example:

https://ipfs.io/ipfs/QmX9kCiaM1oYgQuFmYJwRY3yWXNdY1V8LwQa5U1FcmFy6R

**Comment by chrishobcroft** [comment]
Another example: https://ipfs.io/ipfs/Qma8whJjCQdCn4eBgcx6jtCyRQar8eJipipbpbYZg22SJj

**Comment by haywirez** [comment]
Belongs to [player project](https://github.com/resonatecoop/resonate-crowdfund-player)
