### ISSUE TITLE
Blank space on musicians profiles

### ISSUE THREAD

**Issue by chrishobcroft** [resonatecoop/resonate-crowdfund-uploader#7]
When you try to look at the player, in some cases it comes up with a blank space instead of the player... see link:

https://ipfs.io/ipfs/QmeZGk2tiacLAFPWQcY6iRARMBbCLUM2tJJ1P6CT9y846Q

**Comment by haywirez** [comment]
Should be posted to the [player project](https://github.com/resonatecoop/resonate-crowdfund-player)
